---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sidecar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-sidecar
rules:
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-sidecar
subjects:
- kind: ServiceAccount
  name: cronjob-sidecar