apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-sidecar
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: cronjob_sidecar_image
        imagePullPolicy: IfNotPresent
        name: cronjob-sidecar
        resources:
          limits:
            cpu: 1 
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: /app
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: cronjob-sidecar
      serviceAccountName: cronjob-sidecar
      terminationGracePeriodSeconds: 10