apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shencq
commonLabels:
  app: cronjob-sidecar
resources:
- ../../base
patchesStrategicMerge:
- patches.yaml
images:
- name: cronjob_sidecar_image
  newName: ccr.ccs.tencentyun.com/lzwk/ci-cd-tools
  newTag: dev-sidecar-cronjob-watcher-v0.0.6


